### ISSUE TITLE
cache in the directory created by soft-link

### ISSUE THREAD

**Issue by yizhishang** [Drillster/drone-volume-cache#24]
my java project is yizhishang/k8s-demo, i want to cache the maven repository during drone, and even i want to share  local maven repository to all the project,  so i use "ln -s /mnt/MavenRepo /tmp/cache/yizhishang/k8s-demo/". go errors!! 
![image](https://user-images.githubusercontent.com/12756407/61790792-c22c3200-ae4a-11e9-995c-4a6cd0d7d878.png)

**Comment by yizhishang** [comment]
how to cache and share

**Comment by mjwwit** [comment]
I really don't recommend cache sharing between projects. But if you think you must, here is the way to do it: https://github.com/Drillster/drone-volume-cache/blob/master/DOCS.md#using-the-cache_key-option
Basically you configure all projects that share the same cache to use the same cache key.

Let me know if this works for you.

**Comment by yizhishang** [comment]
in fact, i want all my java projects use one maven repository cache

**Comment by mjwwit** [comment]
That is entirely possible. You'll have to use the same cache key in all your java projects.

**Comment by mjwwit** [comment]
I'm assuming this is fixed now, if not you can re-open it.
