### ISSUE TITLE
Option to isolute cache between matrix builds

### ISSUE THREAD

**Issue by jhasse** [Drillster/drone-volume-cache#3]
For some cases it would be useful to isolate the cache between matrix builds. This is currently possible via `when:`, but one has to repeat a lot, especially when the matrix is big.

**Comment by mjwwit** [comment]
Since the separate matrix build cache adds an extra nested folder, please clear your cache beforehand. You can now also do this by adding `[CLEAR CACHE]` in your commit message.

**Comment by jhasse** [comment]
> You can now also do this by adding [CLEAR CACHE] in your commit message.

Wohhoo awesome! Thanks :)

**Comment by jhasse** [comment]
Is the cache now isolated by default? Because most of the time (e. g. caching `.git/`), I don't want that.

**Comment by mjwwit** [comment]
Yes, the cache is now isolated by default (per matrix job). Caching common stuff (like `.git/`) will still work, the only thing is that `.git/` is cached per job separately.

**Comment by jhasse** [comment]
Okay I can live with that. But for very large caches and huge matrices, some people might miss the old behavior.

**Comment by mjwwit** [comment]
I agree, and I've thought about making it configurable. I'm struggling to figure out a way to cleanly specify which caches to share, and which not to share though. I'm open to ideas about this.

Either way, we'll figure it out soon and implement it.
