### ISSUE TITLE
Cache single files

### ISSUE THREAD

**Issue by bendavies** [Drillster/drone-volume-cache#8]
Hey,

I notice this only seems to support directories at the moment.
I have a single file in the root of my project that i'd like to cache.
Is this something you would consider?

Cheers

**Comment by mjwwit** [comment]
It's definitely something worth looking into. For now, you can work around this by copying the file into a folder, caching that folder, and copying it out again at the beginning of your build.

**Comment by bendavies** [comment]
It doesn't look that hard unless i'm missing something, just an added check for `-f` where you `-d`?
Probably some other subtleties I'm missing. I'll take a look at PRing if i get time.

Thanks for the workaround, i hadn't thought of that!

**Comment by bendavies** [comment]
thanks @mjwwit !
